app_admin_feedback:
  resource: |
    alias: app.feedback
    section: admin
    templates: SyliusAdminBundle:Crud
    redirect: update
    grid: app_admin_feedback
    vars:
        all:
            subheader: app.ui.feedback
        index:
            icon: 'file image outline'
  type: sylius.resource