imports:
- { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }

- { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
- { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }

- { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }

- { resource: "grids/grids.yml" }
- { resource: "@BitBagSyliusWishlistPlugin/Resources/config/config.yml" }



parameters:
  sylius_core.public_dir: '%kernel.project_dir%/public_html'

sylius_shop:
  product_grid:
    include_all_descendants: true
  locale_switcher: storage

sylius_theme:
  sources:
    filesystem:
      directories:
      - "%kernel.project_dir%/themes"

sylius_customer:
  resources:
    customer:
      classes:
        model: App\Entity\Customer

