imports:
- { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }

- { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
- { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }

- { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }

- { resource: "grids/grids.yml" }
- { resource: "@BitBagSyliusWishlistPlugin/Resources/config/config.yml" }
- { resource: "@BitBagSyliusCmsPlugin/Resources/config/config.yml" }
- { resource: "@BitBagSyliusElasticsearchPlugin/Resources/config/config.yml" }


parameters:
  sylius_core.public_dir: '%kernel.project_dir%/public'

sylius_shop:
  product_grid:
    include_all_descendants: true
  locale_switcher: storage

sylius_theme:
  sources:
    filesystem:
      directories:
      - "%kernel.project_dir%/themes"

sylius_customer:
  resources:
    customer:
      classes:
        model: App\Entity\Customer

knp_gaufrette:
  adapters:
    bitbag_sylius_cms_plugin_media:
      local:
        directory: "%kernel.project_dir%/public"
        create: true

sylius_mailer:
  sender:
    name: Yokoso Beauty
    address: info@yokoso-beauty.com

liip_imagine:
  filter_sets:
    sylius_shop_product_original: ~
    sylius_shop_product_tiny_thumbnail:
      filters:
        thumbnail: { size: [64, 64], mode: outbound }
    sylius_shop_product_small_thumbnail:
      filters:
        thumbnail: { size: [112, 112], mode: outbound }
    sylius_shop_product_thumbnail:
      filters:
        thumbnail: { size: [260, 260], mode: outbound }
    sylius_shop_product_large_thumbnail:
      filters:
        thumbnail: { size: [550, 550], mode: outbound }

monolog:
  handlers:
    main:
      type:         fingers_crossed
      # 500 errors are logged at the critical level
      action_level: critical
      # to also log 400 level errors (but not 404's):
      # action_level: error
      # excluded_404s:
      #     - ^/
      handler:      deduplicated
    deduplicated:
      type:    deduplication
      handler: swift
    swift:
      type:       swift_mailer
      from_email: 'info@yokoso-beauty.com'
      to_email:   'nrashidov@gmail.com'
      subject:    'An Error Occurred! %%message%%'
      level:      debug
      formatter:  monolog.formatter.html
      content_type: text/html