App\Entity\Feedback:
  properties:
    name:
      - NotBlank:
          message: sylius.product.name.not_blank
          groups: [app_feedback]
      - Length:
          min: 3
          minMessage: sylius.product.name.min_length
          max: 40
          maxMessage: sylius.product.name.max_length
          groups: [app_feedback]