monolog:
  handlers:
    main:
      type:         fingers_crossed
      action_level: critical
      handler:      grouped
    grouped:
      type:    group
      members: [streamed, deduplicated]
    streamed:
      type:  stream
      path:  '%kernel.logs_dir%/%kernel.environment%.log'
      level: debug
    deduplicated:
      type:    deduplication
      time: 600
      handler: swift
    swift:
      type:       swift_mailer
      from_email: 'info@yokoso-beauty.com'
      to_email:   'nrashidov@gmail.com'
      subject:    'An Error Occurred! %%message%%'
      level:      debug
      formatter:  monolog.formatter.html
      content_type: text/html
