bitbag_sylius_wishlist_plugin:
  resource: "@BitBagSyliusWishlistPlugin/Resources/config/routing.yml"

bitbag_sylius_cms_plugin:
  resource: "@BitBagSyliusCmsPlugin/Resources/config/routing.yml"

#bitbag_sylius_elasticsearch_plugin:
#  resource: "@BitBagSyliusElasticsearchPlugin/Resources/config/routing.yml"

redirect_sylius_shop_product_index:
  path: /taxons/{slug}
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: bitbag_sylius_elasticsearch_plugin_shop_list_products
    permanent: true
  requirements:
    slug: .+
sylius_admin_ajax_product_index:
  path: /admin/ajax/products/
  methods: [GET]
  defaults:
    _controller: App\Controller\CustomController:searchProductAction
    _format: json
app_admin:
  resource: 'routing/admin.yml'
  prefix: /admin
app_shop:
  resource: 'routing/shop.yml'