sylius_grid:
  grids:
    sylius_admin_customer:
      driver:
        options:
          class: App\Entity\Customer
      fields:
        firstName:
          position: 1
        lastName:
          position: 2
        email:
          position: 3
        telegramUsername:
          position: 4
          type: string
          label: telegram_username_short
          sortable: ~
        createdAt:
          position: 5
        enabled:
          position: 6
        verified:
          position: 7
